title: igstan.ro
description: igstan.ro
baseurl:
url: "http://igstan.ro"
permalink: /posts/:year-:month-:day-:title.html
highlighter: pygments
markdown: redcarpet

defaults:
  -
    values:
      layout: post
