title: igstan.ro
description: igstan.ro
baseurl:
url: "http://igstan.ro"
highlighter: pygments
markdown: redcarpet
permalink: /posts/:year-:month-:day-:title.html

defaults:
  -
    values:
      layout: post
